-- Check if ConnectionStringSecretName column exists
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DatabaseCredentials' 
  AND COLUMN_NAME IN ('ConnectionString', 'ConnectionStringSecretName')
ORDER BY COLUMN_NAME;

-- Also check the table structure
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'DatabaseCredentials'
ORDER BY ORDINAL_POSITION;